language: node_js

services:
  - docker

install: true

script:
  - docker build -t registry.heroku.com/aaareviews/web .

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: scotty_aaa

# safelist
branches:
  only:
  - master
  - scotty_aaa
